### ISSUE TITLE
DB用のドキュメントを修正する

### ISSUE THREAD

**Issue by yukihito-jokyu** [yukihito-jokyu/kodomori#39]
以下が記されたドキュメントを作成して欲しい。

- windowsにPostgreSQLをダウンロードする手順
- 本プロジェクトでのPostgreSQLの初期設定
- windowsでPostgreSQLを実装する際の動作手順(ここに初期設定を含めても良い)

**Comment by FukuiSho** [comment]
インストール先
https://www.postgresql.org/
上記のページに移動し、Packages and Installers内のWindowsをクリック
Download the installer をクリック
Windows x86-64の17.2をダウンロード

**Comment by FukuiSho** [comment]
https://qiita.com/waokitsune/items/3a27b7d0ca75bc06b7c0
このドキュメントに従い基本的には選択せずに次を選ぶ。
スタックビルダを選択した場合は、リモートサーバーじゃない方を選択し、次を選ぶ。

**Comment by yukihito-jokyu** [comment]
txtファイルをmdファイルに変更する
