### ISSUE TITLE
データベースを構築するsqlファイルの作成

### ISSUE THREAD

**Issue by yukihito-jokyu** [yukihito-jokyu/kodomori#40]
本プロジェクトの「documents/DB」ディレクトリにあるマークダウンを参照し、定義しているテーブルを作成するsqlファイルを作成して欲しい。

例としてusersテーブルのsqlファイルをここに実装する。この例を参考にして「cameras,dangers,alerts」テーブルを作成するsqlファイルを作成して欲しい。

```sql
-- usersテーブルの作成
CREATE TABLE users (
    user_id VARCHAR(255) PRIMARY KEY,
    is_admin BOOLEAN NOT NULL,
    nursery_school_id VARCHAR(255) NOT NULL,
);
```

※説明
VARCHAR : 文字列
BOOLEAN : ブール値
(255) : 255字まで許容する
PRIMARY KEY : 主キー
NOT NULL : nullは許さない

**Comment by FukuiSho** [comment]
CUIで
psql -h localhost -p 5432 -U postgres -d postgres
で起動

**Comment by FukuiSho** [comment]
テーブルのあるディレクトリまで移動して
psql -h localhost -p 5432 -U postgres -d postgres
でデータベース内に入る
データベースの一覧表示
\l
postgres-# CREATE DATABASE ○○
でデータベースの新規作成
データベースから出る
\q
テーブル一覧の表示
\dt
VScode内のusers.sqlをテーブルに追加
\i users.sql

**Comment by FukuiSho** [comment]
![image](https://github.com/user-attachments/assets/c7a9dc25-d022-46dc-9410-3e2810891377)
![スクリーンショット 2024-12-23 185739](https://github.com/user-attachments/assets/53d82e66-acfe-47b2-bf2c-f2d777e0b248)
